### ISSUE TITLE
这个需要怎么运行呢

### ISSUE THREAD

**Issue by kt5ttk99** [qingchoulove/tunnel#1]

**Comment by qingchoulove** [comment]
目前还没有完成开发的，暂时没有提供可执行文件

**Comment by kt5ttk99** [comment]
自己编译运行的话可以吗

**Comment by qingchoulove** [comment]
需要修改一些代码，有一些调试代码没有push到仓库。是有什么诉求么？可以邮件或Im沟通下

**Comment by kt5ttk99** [comment]
最近在研究对称NAT的P2P打洞功能，但是好像webRTC使用ICE实现的P2P只支持到端口受限-端口受限，后面看了大佬的博客能够端口受限-对称类型的打洞，就想试试

**Comment by qingchoulove** [comment]
可以参照 [tailscale blog](https://tailscale.com/blog/how-nat-traversal-works)
和代码 [code](https://github.com/qingchoulove/tunnel/blob/main/holepunch.go)

单方对称类型是通过端口试探进行的，有一定的成功率

**Comment by qingchoulove** [comment]
修改了下example代码，可以编译example目录自行验证下，先启动server。

**Comment by kt5ttk99** [comment]
好的，谢谢大佬  我试试

**Comment by kt5ttk99** [comment]
大佬，./main -mode server 这样是启动server端吗，我这样运行好像和client是一样的情况
<img width="379" alt="1704968993005" src="https://github.com/qingchoulove/tunnel/assets/71433345/750cbe91-3a57-43c4-8868-4a9183df4be0">

**Comment by qingchoulove** [comment]
先启动server, 然后启动client模式，将输出的nat_detail 复制到对端。因为是demo没有写专门的信令服务来交换offer。
